server:
  port: 8082
spring:
  # Database
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/internal
    username: postgres
    password: postgres
    initializationMode: always
    sqlScriptEncoding: UTF-8
    data: classpath:/data.sql
    continue-on-error: true
  jmx:
    enabled: false

  # JPA properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        format-sql: true
springdoc:
  show-login-endpoint: true
